### ISSUE TITLE
implement numpy.random.shuffle

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#11]
Modify a sequence in-place by shuffling its contents.
https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.shuffle.html

**Comment by Nucs** [comment]
This issue has been implemented in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
