### ISSUE TITLE
Implement numpy.matmul

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#115]
Matrix product of two arrays.
https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matmul.html

**Comment by PppBr** [comment]
I will take this issue

**Comment by henon** [comment]
@PppBr: what is the state of this issue?

**Comment by Nucs** [comment]
This issue has been resolved in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
If it persists, Reopen the issue let us know please.
