### ISSUE TITLE
Implement numpy.transpose

### ISSUE THREAD

**Issue by dotChris90** [SciSharp/NumSharp#117]
Following https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.transpose.html

**Comment by dotChris90** [comment]
Since we don't have a view implementation already. I suggest to have a non view implementation first. That means the transposed output is not a reference to input with different shape and data. Output and input are 2 different memory addresses.

**Comment by letmaik** [comment]
Is it planned to add support for the full numpy api here with the `axes` argument and more than 2D?

**Comment by Oceania2018** [comment]
@letmaik Yes, We will do. Welcome if you could help.

**Comment by Deep-Blue-2013** [comment]
It would be awesome if the axis is added.

**Comment by dotChris90** [comment]
if it is so important we will. :)

**Comment by Nucs** [comment]
`np.transpose` is based on `np.swapaxis` therefore `np.swapaxis` is required first.

**Comment by aidevnn** [comment]
Using a fine transpose across multiple axis can reduce the Tensor Dot to a Matrix Dot and it can  reduce the code with a little performance counterpart.

**Comment by Nucs** [comment]
`np.swapaxes`, `np.transpose`, `np.moveaxis` and `np.rollaxis` were added in the following [this commit](https://github.com/SciSharp/NumSharp/commit/39896599ac40584821802cfd63a15458060289ba ).
And will be released soon in 0.20.4.
