### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by fdncred** [SciSharp/NumSharp#126]
@Oceania2018, I tried to push a change to handle a more broad array of image bpp formats. It appears that my commit permissions have been revoked. If that's the case, this is the change to file `Creation/Numpy.array.cs`.

```cs
imageArray.Shape = new Shape(new int[] { bmpd.Height, bmpd.Width, System.Drawing.Image.GetPixelFormatSize(image.PixelFormat) / 8 });
```
Thanks.

**Comment by Oceania2018** [comment]
We didn't revoke any write access.
![image](https://user-images.githubusercontent.com/1705364/48793442-8e49ad00-ecbc-11e8-8b32-6ef050e42b4b.png)

**Comment by fdncred** [comment]
I have to request permission again. I think it may have to do with changing names to SciSharp. So I clicked request. I assume it's waiting for @Oceania2018 's approval.

![screen shot 2018-11-20 at 12 12 39 pm](https://user-images.githubusercontent.com/343840/48793779-acfc7380-ecbd-11e8-8fa3-e28b19f4cb48.PNG)

**Comment by fdncred** [comment]
fixed
