### ISSUE TITLE
More Abstract properties in classes

### ISSUE THREAD

**Issue by dotChris90** [SciSharp/NumSharp#127]
As we said we want to rewrite the NDArray class I suggest to be more abstract in properties etc. 
This issue is related to #123. 

I mean we should define non generic interfaces like IStorage or INDArray and Storage and ndarray implement them.

Why? Because NDArray could have a property IStorage. Storage is just one implementation. If in future we want redesign it again or do a 2nd implementation of IStorage its easier to rewrite. U could even implement a generic storage but since the interface is non generic the NDArray property also is non generic (runtime type is generic but property is not). 

ASP.NET and all the big framework do like this and we should also think about how interfaces shall look like.

**Comment by Oceania2018** [comment]
We'll discuss further.

**Comment by Oceania2018** [comment]
@dotChris90 Sometimes we need keep it simple. More abstraction will bring more burden for C# programming compiler. Hard to optimize the code.

**Comment by dotChris90** [comment]
As you like. I think with the Array in Storage at moment we are already flexible enough. At least the code looks very flexible.
