### ISSUE TITLE
feature : add method "ToGeneric< T >" to NDArray non generic 

### ISSUE THREAD

**Issue by dotChris90** [SciSharp/NumSharp#130]
this method shall transform the non generic into a generic one.

in this way we do not have to develop extra builder methods to construct generic arrays. we simple use the non generic things to construct non generic and transform to generic.

there will be no memory issue since storage is reference type and so shape and storage simple can be taken from non generic array.

**Comment by Oceania2018** [comment]
I got you.

**Comment by dotChris90** [comment]
already done
