### ISSUE TITLE
np.dot failed

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#136]
The unit test failed for [SciSharp-Learn](https://github.com/SciSharp/SciSharp-Learn).

![image](https://user-images.githubusercontent.com/1705364/49312589-35db9200-f4aa-11e8-8d79-dc84816d1f6b.png)

![image](https://user-images.githubusercontent.com/1705364/49312566-2a886680-f4aa-11e8-8e11-95b70dea0180.png)

**Comment by dotChris90** [comment]
ok I will check.

**Comment by dotChris90** [comment]
ahhhhh damn

the units tests for operations all now for the old ndarrays lol

I was confused before and asking "Why unit tests not fail before?"

**Comment by Oceania2018** [comment]
@dotChris90 has fixed it.
