### ISSUE TITLE
Implement linalg.lstsq

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#144]
Return the least-squares solution to a linear matrix equation.
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.lstsq.html

**Comment by dotChris90** [comment]
@Oceania2018 After QR now will try dgels_ but .... get the "memory corruption" error -.- when finding out the correct cast values, can do this lstsq

**Comment by dotChris90** [comment]
@Oceania2018 I will keep this issue open - the implementation at moment just return the param array - but according to numpy doc - there are much more output like residuals, rank, singular values, ...

**Comment by Oceania2018** [comment]
really, I thought _umath_ is another library.

**Comment by dotChris90** [comment]
not sure. I just know the portable windows python version have just one lapack lite. but year u are right the normal python has a 2nd dll there

**Comment by dotChris90** [comment]
This need to implement the other return types like error etc
