### ISSUE TITLE
Use implicit conversions to simplify element access

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#154]
I happened to see some examples of using implicit conversions. It feels very good. If we can use to access ndarray's element, the code will look very clean.

```cs
Digit dig = new Digit(7);

// This call invokes the implicit "double" operator
double d1 = dig;
```
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/implicit

**Comment by dotChris90** [comment]
@Oceania2018 DAMN! I did not know it exist. This is so cool. We do not need the ToDotNetArray method but can use such things. ;)

**Comment by dotChris90** [comment]
we should start a folder "convert" or "casting" because with this we get a lot scenarios

**Comment by dotChris90** [comment]
sth like this would be awesome

NDArray A = {{1.0,2.0},{3.0,4.0}};

not sure if easy to reach

**Comment by Oceania2018** [comment]
@dotChris90 , do some experiment, can't wait. I'm focused on [TensorFlow.NET](https://github.com/SciSharp/TensorFlow.NET) currently. Hope you get it out. But no rush, we could add this feature for v0.7.

**Comment by dotChris90** [comment]
@fdncred thanks. :D great what cool things are possible with C# ;)

**Comment by dotChris90** [comment]
I close this because .NET arrays now can be implicit cast from and to NDArray
