### ISSUE TITLE
Index selection in ndarray doesn't work

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#170]
After upgrading to v0.6, can't compile:
![image](https://user-images.githubusercontent.com/1705364/50422575-161d5c80-0811-11e9-9b4e-cb1ececd1253.png)
It should be working like this:
![image](https://user-images.githubusercontent.com/1705364/50422526-d8203880-0810-11e9-9383-4681e5c4a407.png)

**Comment by dotChris90** [comment]
ok in process with this unit test and for 1D arrays

```CSHARP
public void NDArrayByNDArray()
        {
            NDArray x = new double[] {1,2,3,4,5,6};

            NDArray index = new int[] {1,3,5};

            NDArray selected = x[index];

            double[] a = (System.Array) selected as double[];
            double[] b = {2,4,6};

            Assert.IsTrue(Enumerable.SequenceEqual(a,b)); 
        }
```
