### ISSUE TITLE
Can't create value by single string

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#174]
In Tensorflow.NET, I can't do:
`var tensor = tf.constant("Elephant");`
```cs
public static Tensor constant(NDArray value, string name = "Const", bool verify_shape = false)
{
    return constant_op.Create(value, name, verify_shape);
}
```
It should work, but exception throw:
![image](https://user-images.githubusercontent.com/1705364/50493203-a3afa680-09e1-11e9-990f-0ee95b8a1557.png)

**Comment by dotChris90** [comment]
@Oceania2018 ok checked it. before it was just designed for "[1,2,3;4,5,6]" syntax - so parsing string matrix. But will change - if it can not find[] will add it as scalar string.

**Comment by dotChris90** [comment]
@Oceania2018 one question - or should we totally remove this implicit string cast? 

otherwise we get problems maybe to decide if matrix parse or not. Should we always cast every automaticly to string scalar?

**Comment by dotChris90** [comment]
@Oceania2018 if you can work with this - close issue ;) or if still problem - let me know

**Comment by Oceania2018** [comment]
I can try to use RegEx to identity string pattern.
