### ISSUE TITLE
Shape changed when Storage.Allocate is called

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#177]
@dotChris90 Please run `np.random.normal.Test`, the output ndarray should keep the shape.
This issue is also mention on https://github.com/Proxem/NumNet/issues/2. I can't fix it due to the layout logic. 

![image](https://user-images.githubusercontent.com/1705364/50530223-12176600-0ac1-11e9-8484-58a2310cfb4c.png)

**Comment by dotChris90** [comment]
@Oceania2018 yes the allocate shall never be called after storage is already created. >.< sorry was not too obviously. 

The constructor with int as inputs already create a correct shape - so all you need to do is **Storage.SetData**. I already pushed fix to my repo and will merge here. 

Also extended the Unit Test - so we can be sure the shape is kept inside. Now shape is tested. 

```CSHARP
            double mu = 0; // mean
            double sigma = 0.1; // standard deviation
            var s = np.random.normal(mu, sigma, 10, 100);

            Assert.IsTrue(Math.Abs(mu - mean.Data<float>()[0]) < 0.01);
            Assert.IsTrue(s.shape[0] == 10);
            Assert.IsTrue(s.shape[1] == 100);
```

**Comment by dotChris90** [comment]
@Oceania2018 please check again - if you satisfied close ticket if not - let me know. ;)
