### ISSUE TITLE
Implicit from anonymous object

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#182]
We should create NDArray like below:

![image](https://user-images.githubusercontent.com/1705364/50541846-e30dfc80-0b73-11e9-9dc5-7ddd3ba83b81.png)

![image](https://user-images.githubusercontent.com/1705364/50541841-de494880-0b73-11e9-9f94-799265098735.png)

**Comment by dotChris90** [comment]
@Oceania2018 are you sure this is possible?

NDArray arr = new int[]{1,2,3,4} ; // this is fine because compiler knows type 
NDArray arr2 = {1,2,3} ; // not sure because this is a specific array expression >.<

**Comment by Oceania2018** [comment]
Seems it is impossible to implement. Close.
