### ISSUE TITLE
Jagged arrays are not allowed here!

### ISSUE THREAD

**Issue by Esther2013** [SciSharp/NumSharp#186]
When I use Implicit converting for `new int[][] { new int[] { 3, 3 } }`, exception throws.

![image](https://user-images.githubusercontent.com/33488376/50733493-28be5c80-1154-11e9-9b48-1c22c9cd8c57.png)

![image](https://user-images.githubusercontent.com/33488376/50733494-31169780-1154-11e9-840b-bfb06714c333.png)

**Comment by dotChris90** [comment]
If you want - we can add this feature. 

I will try to create one independent of ndim.

**Comment by Esther2013** [comment]
@dotChris90 , Yes please add it.

**Comment by dotChris90** [comment]
check latest state - after #189 it should be possible. unit tests at moment just check for 2D.

**Comment by Esther2013** [comment]
Works, appreciate.
