### ISSUE TITLE
Index access returns incorrect data type

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#191]
![image](https://user-images.githubusercontent.com/1705364/51881885-7dfc2100-2342-11e9-94c2-bb90e62ccc16.png)

**Comment by dotChris90** [comment]
sorry didn't get what you mean. if it's really a bug could we think about a unit test instead of python code?

**Comment by Oceania2018** [comment]
@dotChris90 Please check the unit test `IndexingTest.NDArrayAccess`

**Comment by dotChris90** [comment]
thanks. will do

**Comment by emrahsungu** [comment]
As far as I could see, the current implementation of NDArray indexers only return a single value where they should return NDARRAY of `ndim - indexers.Length`?

**Comment by Oceania2018** [comment]
@emrahsungu Yes, your are right. return an new `NDArray` with ndims.

**Comment by emrahsungu** [comment]
I just want to make sure before I take on the job, I also see that the implementation of Indexers are also not completed at all and will require an overhaul, right? Especially, the indexer which takes NDArray

**Comment by Oceania2018** [comment]
@emrahsungu if you can make the unit test `IndexingTest.NDArrayAccess` pass, It will be OK.
```csharp
        [TestMethod]
        public void NDArrayAccess()
        {
            var nd = np.arange(4).reshape(2, 2);

            var row1 = nd[0];
            // Assert.AreEqual(row1.GetType(), typeof(NDArray));
            // Assert.AreEqual(row1[0][0], 0);
            // Assert.AreEqual(row1[0][1], 1);
        }
```

**Comment by emrahsungu** [comment]
@Ocenia2018, thanks for the swift response. I have seen the unit test but what I am concerned is that it looks like Indexer which takes NDArray as parameter is not fully implemented and requires a bit of an overhaul.  Are we on the same page?😀

**Comment by Oceania2018** [comment]
Yes we need an overhaul. I think it will return a object, When ndim = 0 then return scalar value, when ndim == input.ndim then rerun scalar value, when ndim < input.ndim then return ndarray. And add an implicit to convert between ndarray and ndarray when the ndim is different. I haven’t find the best solution.

**Comment by emrahsungu** [comment]
@Oceania2018 Yeah I had something similar in my mind. I will try the challenge. Hopefully, I can come up with a nice solution.

**Comment by Oceania2018** [comment]
Considering the performance and long term goal which is becoming productivity, I want to refactor NumSharp v2.x based on ArrayFire.

**Comment by Oceania2018** [comment]
We will change our storage to unmanaged memory. We can discuss on another thread if have interested on the 2.x plan.

**Comment by Oceania2018** [comment]
You can still working on current branch if you want, because the high level will not going to be changed.

**Comment by emrahsungu** [comment]
Sure I would love to hear more!

**Comment by Oceania2018** [comment]
@emrahsungu raised new issue of #195
