### ISSUE TITLE
numpy.prod

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#194]
Return the product of array elements over a given axis.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.prod.html

**Comment by Nucs** [comment]
This issue has been implemented in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
