### ISSUE TITLE
Refactor NumSharp in Branch 2.x

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#195]
In order to make NumSharp more practical, we plan to open a new branch and refactor the NumSharp kernel to build based on ArrayFire. The purpose of this is to make NumSharp perform better and the data will be stored entirely in unmanaged memory. Easier to implement the `view` of `ndarray` function Take advantage of ArrayFire's sophisticated underlying computing framework to make NumSharp easy to use GPU resources.
First we need to improve the [array-dotnet](https://github.com/SciSharp/arrayfire-dotnet) project, and NumSharp then encapsulates the numpy syntax based on it.

More contributors are welcome to join SciSharp STACK to discuss or submit code.

**Comment by emrahsungu** [comment]
> data will be stored entirely in unmanaged memory.

I would like to hear more about this. Is the memory going to be left to `arrayfire`? There will be marshalling back and forth?

**Comment by Oceania2018** [comment]
As long as you avoid repeatedly accessing elements in managed memory, there is no problem, and transfer computation to low level c++. The performance improvement is worthwhile. Especially for the intensive calculation of machine learning model training.

**Comment by Oceania2018** [comment]
ArrayFire only support up to 4 dimensions.

**Comment by dotChris90** [comment]
@Oceania2018 yes the 4 dimension limitation is also something I read in their documentation. 
But I think we have to find a way to overcome this limitation since I think some Numpy people will do it and when computing take parts of the tensor, e.g. have a 3x3x2 tensor and "cut" out 2 matrix 3x3 and 3x3. 

But you are right - it is an extreme nice to use library. 
There are some points we could check (and I already started). 

- I think I read that it is possible in arrayfire to get a C pointer back from their array class (as a view) 
- unfortunately setting up all and even interact from C# with their lib took longer than expected and so point 1 (C pointer as view) is still unchecked from my side
- most important! it must be a view!
- If we really could get back such a view as C Pointer we can bring it into C# area (maybe even as fancy new Span or Memory class) and! it will be the same memory area in C# and C
- It would be extreme nice if we can "see" this array not just in unmanaged C world but also in C# level because it makes things easier (especially debugging)

**Comment by Oceania2018** [comment]
Good point. I am a little hesitant, we might just refactor our storage first, in order to implement `numpy view`.

**Comment by dotChris90** [comment]
thats fine! :) first clear all things here before we start. But Haiping - with Arrayfire you already found an extreme good to use and good performance library. I totally agree - we must (somehow) integrate them.  

Until now I was very surprised how easy Span can be used with arrayfire. 

Example : 

if define

```CSharp
public class AF
{
        [DllImport("af.dll")]
    	public static extern int af_create_array(out IntPtr array_arr, [In] float[] data, uint ndims, [In] long[] dim_dims, int type);
        [DllImport("af.dll")]
        public static extern int af_get_data_ptr(ref float data, IntPtr array);
}

```

you can use : 

```CSharp
float[] data = {1,2,3,4,5};

int z = AF.af_create_array(out ptr, data, (uint)data.Rank,new long[]{data.Length},0);

System.Span<float> a = new float[5];

z = AF.af_get_data_ptr(ref MemoryMarshal.GetReference(a), ptr);
```

But this is a copy .... the Span in C# is not the same memory like in C. Found it out by got a 2nd Span and changed 1st one - 2nd was not affected.

**Comment by Oceania2018** [comment]
@dotChris90 It's not perfect. Let's don't use managed memory `Span` or `Memory` operations. We'll all use unmanaged memory if we use `ArrayFire`. Because we might pass data between process. Have you took about the `Apache Arrow` project? They share data between different projects.

**Comment by Oceania2018** [comment]
@dotChris90 @emrahsungu I decided to adopt a multi-kernel architecture mechanism that supports both default Tensor or ArrayFire or other open source Tensor computing libraries.

**Comment by deepakkumar1984** [comment]
There was a project by Alex-Weaver "TensorSharp" which I tried to use for building a neural network library. The library had all the basic math, elementwise, dimensionwise ops well written in C++ and have a C# wrapper on the top of it. It's also integrated with ManagedCuda which can be built with any Cuda version from 8.0 till 10. The size of the library is small to around 4 MB and doesn't need any separate installation, can be embedded within NumSharp library. The only problem with using ArrayFire is the big dependency on another product which can be overcome with having built-in functions.

https://github.com/SciSharp/SiaNet/tree/master/Backends/SiaNet.Backend.TensorSharp/Cpu
https://github.com/SciSharp/SiaNet/blob/master/Backends/SiaNet.Backend.TensorSharp/Ops.cs

There are the equivalent CUDA operations as well.

C++ ops implemented:
https://github.com/SciSharp/SiaNet/blob/master/Library/CpuOps/DimensionwiseOps.h
https://github.com/SciSharp/SiaNet/blob/master/Library/CpuOps/ElementwiseOps.h
.. more

Please give a thought if you think we can merge these functions within NumSharp without any external dependencies, makes it easy to use.

**Comment by Oceania2018** [comment]
It's good idea. I'll look at your code deeply. you didn't PR to TensorSharp?
I'm thinking how to integrate to NumSharp, from your fork or TensorSharp master ?

**Comment by deepakkumar1984** [comment]
There was lot of refactor and added dependency on bit of customized
managedcuda project, so only didn't raised PR. I will do that in next 2
days and see can be accepted.
