### ISSUE TITLE
numpy.argsort

### ISSUE THREAD

**Issue by Esther2013** [SciSharp/NumSharp#197]
Returns the indices that would sort an array.
https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.argsort.html

**Comment by Oceania2018** [comment]
@emrahsungu Could you make the ndarray.argsort more generic that supports axis? I just made the simple version.

**Comment by emrahsungu** [comment]
@Oceania2018, I will have a look right away. Generic, as in not just for ndim==1 right?
https://github.com/SciSharp/NumSharp/blob/3dd1ff017ac7f0fb48ea0c4bcb2913e38e4c0994/src/NumSharp.Core/Extensions/ndarray.argsort.cs

**Comment by Oceania2018** [comment]
@emrahsungu Yes, you are definitely right. Appreciate you take that job.

**Comment by Oceania2018** [comment]
Any progress?

**Comment by emrahsungu** [comment]
Hi there, I am simply sorry for no progress. I am working 9am - 11pm currently because we are on a deadline for our next game. I only have weekends to look at the code 😭. Good news you get to see new Pokemons 🤣

**Comment by emrahsungu** [comment]
@Oceania2018, I just created a pull request for the Issue. Sorry for the comments, I will fix them when I have more time at hand

**Comment by Oceania2018** [comment]
@emrahsungu , awesome, we appreciate. Your commits are making NumSharp better. @dotChris90 , we should welcome Sungu again.

We have one coding principle:
Try to avoid using LINQ especially in the intensive loop function. (sometimes LINQ is not good as we thought). 
`Enumerable.Range(0, iterateUntil).Select(_ => previousStep.Concat((_).Yield()));`
is not good as the simple `for (int i = 0; i < iterateUntil; i++)`;
And the `Yield` is bad performance.
You don't have to change it right away. 
We did some performance discuss before:
https://github.com/SciSharp/NumSharp/issues/14
https://github.com/SciSharp/NumSharp/issues/63

**Comment by emrahsungu** [comment]
Thanks for the comments, I really appreciate it. Like you mentioned LINQ comes with an overhead about 1.40 times of the simple for loop. I usually choose it for the expressiveness. I have not tested the simple Enumerable.Range case but it definitely should be slower than the similar for loop. I will fix it as soon as I have some time.

Can you please tell me more about the Yield() bad performance? We use it on AI servers such as skill selection etc

**Comment by Oceania2018** [comment]
I've not test `yield` yet, just know from this [post](https://stackoverflow.com/questions/3969963/when-not-to-use-yield-return).
