### ISSUE TITLE
Missing last data when ToString()

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#200]
It should be showing as [1, 2, 0].

![image](https://user-images.githubusercontent.com/1705364/53305373-7ac35a80-3846-11e9-9333-80383bdb9ea7.png)

**Comment by dotChris90** [comment]
will check after work. can't be too difficult.

**Comment by emrahsungu** [comment]
Not just this one but I am worries about the checking ndim for 0 2 or other through out the source code.

**Comment by henon** [comment]
ToString was completely rewritten by me some time ago. This issue is out of date. Closing.
