### ISSUE TITLE
compare numsharp's matrix and MathNet.Numerics.LinearAlgebra.Matrix

### ISSUE THREAD

**Issue by pkingwsd** [SciSharp/NumSharp#201]
ENV: win10 , numsharp0.73 , MathNet4.7+mkl   
the code as bellow
            var aArray = new float[1024 ];
            var bArray = new float[1024 * 110000];
            var a = np.asarray<float>(aArray).reshape(1, 1024);
            var b = np.asarray<float>(bArray).reshape(1024, 110000);            
            var c = np.dot(a,b); // 327ms ;

            var Vectora = MathNet.Numerics.LinearAlgebra.Vector<float>.Build.Dense(aArray);
            var matrixb = MathNet.Numerics.LinearAlgebra.Matrix<float>.Build.DenseOfRowMajor(110000, 1024, bArray);

            var matrixc = matrixb * Vectora; // 27ms

numsharp -- 327ms 
MathNet  --- 27 ms

**Comment by Oceania2018** [comment]
@emrahsungu @dotChris90 Do you guys have any idea about this performance issue? Let's work together to improve it.

**Comment by emrahsungu** [comment]
Oh ten times?!😭

**Comment by emrahsungu** [comment]
I don't know how much it affects but for starters tamath.net looks like it is using native providers

**Comment by emrahsungu** [comment]
@Oceania2018 @dotChris90 Oh I see why NumSharp performs bad in dot product. Dot product by definition is highly parallelize-able(← I do not know if this is an actual word) Math.Net uses Parallel Library for dot product where as  NumSharp is not.

**Comment by Oceania2018** [comment]
@emrahsungu Could you paste sample code of Math.NET?

**Comment by emrahsungu** [comment]
In file `ManagedLinearAlgebraProvider.Single.cs`

` CommonParallel.For(0, rowsX, 1, (u, v) =>
                {
                    var row = new float[columnsX];
                    for (int i = u; i < v; i++)
                    {
                        GetRow(Transpose.DontTranspose, i, rowsX, columnsX, x, row);
                        for (int j = 0; j < columnsY; j++)
                        {
                            var column = columnDataB[j];
                            float sum = 0;
                            for (int ii = 0; ii < row.Length; ii++)
                            {
                                sum += row[ii] * column[ii];
                            }

                            result[j * rowsX + i] += 1.0f * sum;
                        }
                    }
                });`

**Comment by emrahsungu** [comment]
In file `ManagedLinearAlgebraProvider.Single.cs`

```  
CommonParallel.For(0, rowsX, 1, (u, v) =>
                {
                    var row = new float[columnsX];
                    for (int i = u; i < v; i++)
                    {
                        GetRow(Transpose.DontTranspose, i, rowsX, columnsX, x, row);
                        for (int j = 0; j < columnsY; j++)
                        {
                            var column = columnDataB[j];
                            float sum = 0;
                            for (int ii = 0; ii < row.Length; ii++)
                            {
                                sum += row[ii] * column[ii];
                            }

                            result[j * rowsX + i] += 1.0f * sum;
                        }
                    }
                });```

**Comment by Oceania2018** [comment]
Is the `CommonParallel` equivalent `Parallel.ForEach`?

**Comment by emrahsungu** [comment]
@Oceania2018 In the internals it calls `Parallel.ForEach`

**Comment by Oceania2018** [comment]
@emrahsungu They use multiple core in `Paralle.ForEach`, Could you help optimize NumSharp `dot` function?

![image](https://user-images.githubusercontent.com/1705364/53684531-23087180-3cd4-11e9-8ec9-349af110a716.png)

**Comment by emrahsungu** [comment]
@Oceania2018 Should be child's play to change implementation into a parallel one

**Comment by Oceania2018** [comment]
@emrahsungu Sorry, What do you mean? Do you think we are going to refactor in ArrayFire?

**Comment by emrahsungu** [comment]
@Oceania2018 , Absolutely I will try to optimize NumSharp.dot operation using Parallel approach

**Comment by emrahsungu** [comment]
What I meant is that I will try to optimize `NumSharp.dot` operation using `Parallel Library`

**Comment by Oceania2018** [comment]
Sounds great.
