### ISSUE TITLE
Implement np.save

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#213]
Save an array to a binary file in NumPy .npy format.
https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.save.html

**Comment by Oceania2018** [comment]
@dania-vera Please update issue status, seems like you already finished it.

**Comment by dania-vera** [comment]
@Oceania2018 This issue is already finished. You can close it.

**Comment by dania-vera** [comment]
Both format are supported .npy and .npz.
