### ISSUE TITLE
NDArray.transpose()

### ISSUE THREAD

**Issue by pkingwsd** [SciSharp/NumSharp#222]
like this:

        img4 = np.array(img3)[:,:,::-1]
        img5 = img3.transpose(0,3,1,2)

**Comment by henon** [comment]
duplicate of [117](https://github.com/SciSharp/NumSharp/issues/117)

**Comment by Nucs** [comment]
`np.swapaxes`, `np.transpose`, `np.moveaxis` and `np.rollaxis` were added in the [this commit](https://github.com/SciSharp/NumSharp/commit/39896599ac40584821802cfd63a15458060289ba ).
And will be released soon in 0.20.4.
