### ISSUE TITLE
Float datatype support in np.load

### ISSUE THREAD

**Issue by DmitryGeyzersky** [SciSharp/NumSharp#224]
Is there any planned support for f4 (float) datatype in np.load method?
Something like this would be extremely useful:

`np.Load<float[]>(@"test.npy");`

**Comment by Oceania2018** [comment]
@dania-vera Is it possible for you?

**Comment by dania-vera** [comment]
@Oceania2018  I just see your comments right now. After a sick week, I'm coming back tomorrow to the office. No, I don't have the option to close both issues.

**Comment by Oceania2018** [comment]
I mean the np.Load<float[]>(@"test.npy");

**Comment by domtheluck** [comment]
Should be great to have float (f32/f64) support in np.save as well.

**Comment by Oceania2018** [comment]
@DmitryGeyzersky Could you check it?

**Comment by DmitryGeyzersky** [comment]
@Oceania2018 , thank you for the update! I've tested it on my files and it works like a charm.
Thank you!

Dima
