### ISSUE TITLE
wrong result from np.dot

### ISSUE THREAD

**Issue by Hmean** [SciSharp/NumSharp#227]
I am a beginner, I want to use numpy in C#, so...
But I find the result from numsharp.dot is different with numpy.
There are my  C# code:
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NumSharp.Core;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var a = np.array(new int[,] { { 1, 2 }, { 1, 2 } });
            var b = np.array(new int[,] { { 1, 2 }, { 1, 2 } });
            var c = a.dot(b);
            var d = a * b;
            Console.WriteLine("c:{0}\nd:{1}", c, d);
            Console.ReadKey();
        }
    }
}`
The result is ：
   c:array([[ 1,  4],
                [ 1,  4]])
   d:array([[ 1,  4],
                [ 1,  4]])
But the right result should be ：
   c:array([[ 3,  6],
                [ 3,  6]])
   d:array([[ 1,  4],
                [ 1,  4]])
What's wrong with my code?

**Comment by Oceania2018** [comment]
Will fix it

**Comment by Oceania2018** [comment]
@Hmean Try to upgrade to v0.8.3, thanks.

**Comment by Hmean** [comment]
That's all ok
