### ISSUE TITLE
Error when installing via NuGet

### ISSUE THREAD

**Issue by fr0** [SciSharp/NumSharp#229]
I'm using VS2015 on Windows 10.

When I try to install `NumSharp` using nuget in Visual Studio, I get the following error: 

```
Could not install package 'NumSharp 0.8.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

I tried changing to .NET 4.6.1 but I got a similar error.

**Comment by Oceania2018** [comment]
I use VS 2017 Community and Windows 10. I can not reproduce it due to lack of environment like yours.

**Comment by fr0** [comment]
I will try installing VS2017 Community.

**Comment by fr0** [comment]
It successfully installed via NuGet on VS2017, so I was able to get past it. Thanks.
