### ISSUE TITLE
Get the vector in the dimension

### ISSUE THREAD

**Issue by LinusKimi** [SciSharp/NumSharp#235]
ONE :
1. In Python ：
    2 axis:
    x = np.arange(12).reshape(3, 4)
    print(x[1])    // [4 5 6 7]
    3 axis:
    nd = np.arange(12).reshape(2, 3, 2)
    print(nd[0])    // [ [0 1] [2 3] [4 5] ]
    print(nd[1])    // [ [ 6  7] [ 8  9] [10 11] ]

2. In NumSharp ：
    // create a tensor
    var nd = np.arange(12).reshape(2, 3, 2);
    
    var data_0 = nd[new Shape(0)];    // [ [ 0 1] [ 2 3] [ 4 5] ]
    var data_1 = nd[new Shape(1)];    // [ [ 0 1] [ 2 3] [ 4 5] ]

There may be something wrong with this data ?

**Comment by Oceania2018** [comment]
@LinusKimi We're refactor the indexing function, once this finished, all the index will return the `ndarray` object.
