### ISSUE TITLE
Mimic np [:,:] behavior

### ISSUE THREAD

**Issue by atotalnoob** [SciSharp/NumSharp#243]
Hi, 

How would I mimic np [:,X] or [X,:] behavior in numSharp?

**Comment by henon** [comment]
duplicate of https://github.com/SciSharp/NumSharp/issues/238 please check it out

as of now it is not entirely implemented

**Comment by Oceania2018** [comment]
We'll wait for .net standard 2.1, it introduces new syntax to index: https://github.com/dotnet/csharplang/issues/2148

**Comment by Esther2013** [comment]
Currently we use `string` as indexing, it works so far.

**Comment by henon** [comment]
please discuss further at #238
