### ISSUE TITLE
Need help loading Tiff/Raw Grayscale Image to NDArray

### ISSUE THREAD

**Issue by thefsm93** [SciSharp/NumSharp#244]
Hey SciSharp/NumSharp Team!

So I'm sorry to bother you guys here, but I've been working on converting some NumPy code over to C# and I thought this would be the right library to use.

Problem is, I can't seem to figure out how in the world to use y'alls library in the same fashion as NumPy. For example, in NumPy I could just do np.fromFile() or np.fromBuffer in order to load up a tiff gray-scale image to pull a float32 array. 

Could you provide me with an example on how to load a tiff or raw grayscale file into an NDArray?

Thanks!

**Comment by Oceania2018** [comment]
Hi, 

Could you raise this issue/ requirement to NumSharp’s issue page on GitHub. So we can track it and other people may help you.

Thanks,
Haiping Chen

**Comment by thefsm93** [comment]
Ahhh I thought that was where this was. Sure absolutely!

**Comment by Oceania2018** [comment]
Sorry, I just got it from email. So it's fine here. thanks.

**Comment by thefsm93** [comment]
Reopened, although I did open one over there also :)

**Comment by Oceania2018** [comment]
Acutall we used to wrote a sample code to load image.

![image](https://user-images.githubusercontent.com/1705364/56062332-a389ab80-5d31-11e9-993e-d981d628b511.png)

**Comment by thefsm93** [comment]
Gonna give this a shot and see if it works!

**Comment by thefsm93** [comment]
Worked! Thanks!

**Comment by Oceania2018** [comment]
BTW, the performance is good?

**Comment by thefsm93** [comment]
On the small test file, yes. However I've run into a different problem with
the full 128MB raw file. It's an issue outside of NumSharp though :)
