### ISSUE TITLE
Help Needed to Convert tiff/raw image to NDArray

### ISSUE THREAD

**Issue by thefsm93** [SciSharp/NumSharp#245]
Hello NumSharp Team!

So I'm sorry to bother you guys here, but I've been working on converting some NumPy code over to C# and I thought this would be the right library to use.

Problem is, I can't seem to figure out how in the world to use y'alls library in the same fashion as NumPy. For example, in NumPy I could just do np.fromFile() or np.fromBuffer in order to load up a tiff gray-scale image to pull a float32 array.

Could you provide me with an example on how to load a tiff or raw grayscale file into an NDArray?

Thanks!

**Comment by Oceania2018** [comment]
https://github.com/SciSharp/NumSharp/blob/v0.5-dtype/src/NumSharp.Core/Creation/NumPy.array.cs

**Comment by thefsm93** [comment]
Let me try this and see if that works! Thanks!

**Comment by thefsm93** [comment]
That worked! Wow I can't believe I didn't figure that out, thanks for the super fast response!
