### ISSUE TITLE
np.sum

### ISSUE THREAD

**Issue by deepakkumar1984** [SciSharp/NumSharp#251]
Implement np.sum
https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html

**Comment by Oceania2018** [comment]
![image](https://user-images.githubusercontent.com/1705364/56361270-8d09a700-61ac-11e9-9f98-e999c110d906.png)

I'll expose `sum` to `np`. You can use it as extension temporarily.

**Comment by Oceania2018** [comment]
Oh, I saw you already assigned to yourself. Are you going to PR?

**Comment by deepakkumar1984** [comment]
The function is adding two NDArray, elementwise. I think the Add function does that already. it should be Sum of array elements over a given axis. So the parameter need to be an axis.

**Comment by henon** [comment]
https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.sum.html

there is also a link to the source code on the top right corner which can often be directly ported to implement the function.

**Comment by deepakkumar1984** [comment]
Hi, seems there is an issue with np.sum for axis -1. The result I am getting is SumAll whereas should be sum at axis -1 which for 2D will be 1, 3D will be 2.

Python version:
![image](https://user-images.githubusercontent.com/6328361/56873249-333c9300-6a70-11e9-941c-36901311510c.png)

In NumSharp I get 45 for the same invoke.
![image](https://user-images.githubusercontent.com/6328361/56873286-7565d480-6a70-11e9-814b-9cabe881e0a3.png)

**Comment by Oceania2018** [comment]
OK, -1 means last axis. Will add next release.

**Comment by henon** [comment]
by the way, many NumSharp methods use -1 for the default axis right now. these will all have to be changed to use int? instead of int for axis and use null instead of -1 for the default axis

**Comment by Oceania2018** [comment]
Oh, I will fix them one by one.

**Comment by Plankton555** [comment]
This bug has not been fixed (at least not merged into master). The implementation of [NDArray.sum.cs](https://github.com/SciSharp/NumSharp/blob/master/src/NumSharp.Core/Math/NDArray.sum.cs) does not sum the elements, but counts the number of elements that are equal, just like @deepakkumar1984 stated in [his reply](https://github.com/SciSharp/NumSharp/issues/251#issuecomment-484765480). I saw that this old issue existed when I was about to create a new one regarding the bug.

**Comment by Nucs** [comment]
np.sum and many np.* functions are limited to 2 dimensions. this is part of a work in progress on my local.

**Comment by Nucs** [comment]
This issue should be resolved in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
If it persists, Reopen the issue let us know please.

**Comment by PavanSuta** [comment]
I am in v4.0.30319, sum function is still not working.
