### ISSUE TITLE
numpy.random.uniform

### ISSUE THREAD

**Issue by deepakkumar1984** [SciSharp/NumSharp#252]
https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.public .html

**Comment by Oceania2018** [comment]
@deepakkumar1984  I Can't open this link.

**Comment by deepakkumar1984** [comment]
This is the link: https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.uniform.html

**Comment by Nucs** [comment]
Added in PR #283
