### ISSUE TITLE
np.repeat results in all zeros

### ISSUE THREAD

**Issue by rbloching** [SciSharp/NumSharp#253]
When using the repeat method:

```cs
var arr = np.repeat(99,10);
var size = arr.size;            
Console.WriteLine("size = " + size);
Console.WriteLine(arr.ToString());
```

size will be correct (10), but the resulting array is set to all 0's

**Comment by Oceania2018** [comment]
@rbloching It works on my side. What version are you using?

![image](https://user-images.githubusercontent.com/1705364/56471886-3fe03c00-641d-11e9-805e-51d490d1e918.png)

**Comment by rbloching** [comment]
It was ran from the master branch. Just confirmed this works when running from 0.9-view.
