### ISSUE TITLE
Missing API's

### ISSUE THREAD

**Issue by deepakkumar1984** [SciSharp/NumSharp#254]
np.full: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.full.html
np.exp: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.exp.html
np.clip: https://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html
np.around: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.around.html

Need this to complete the NeuralNetwork example for NumSharp, also will have some real examples like Titanic Survival, Boston Housing, MNIST etc

**Comment by Oceania2018** [comment]
@Nucs Could you help on these missing APIs ?

**Comment by Nucs** [comment]
Sure, assign it to me.

**Comment by Oceania2018** [comment]
You have to accept the invitation. Then I can assign ticket to you.

**Comment by Nucs** [comment]
All features were implemented in NumSharp 0.20.4.
