### ISSUE TITLE
NDArray multiply error

### ISSUE THREAD

**Issue by zhaoyipeng** [SciSharp/NumSharp#262]
these codes will report error
```python
NDArray l = np.arange(10);
l  = l * 2.0;

```

**Comment by zhaoyipeng** [comment]
I changed the NDArray to float64, it can run

```python
NDArray l = np.arange(10.0);
l  = l * 2.0;
```

**Comment by Oceania2018** [comment]
Yes, because the left operand and right operand is different data type. We disabled the data type converting implicitly due to performance consuming.
