### ISSUE TITLE
latest release broke my code

### ISSUE THREAD

**Issue by fr0** [SciSharp/NumSharp#271]
Upgraded from 0.8.3 to 0.10.1, code that used to work is now throwing an exception:

![exception](https://user-images.githubusercontent.com/435418/57571880-61f82900-73e1-11e9-9ed0-81a42f1cdf29.png)

`array` is a plain `NDArray`

Here's the (relevant) stack trace:
```
   at NumSharp.Backends.TypedArrayStorage.GetSpanData[T](Slice slice, Int32[] indice)
   at NumSharp.NDArray.GetData(Int32[] indices)
   at NumSharp.NDArray.get_Item(Int32[] select)
```

**Comment by Oceania2018** [comment]
Hi thanks for submitting the issue. It would be great if you can PR a UnitTest to reproduce your situation.

**Comment by fr0** [comment]
Thanks for the reply. I don't know how to write a unit test, but reproducing it is very easy:

```
using NumSharp;
using NumSharp.Generic;
using System;

namespace ConsoleApp1
{
  class Program
  {
    static void Main(string[] args)
    {
      var array = new NDArray<int>(new Shape(10, 10));
      Broken(array.transpose());
    }

    static void Broken(NDArray array)
    {
      for (var i=0; i<array.shape[0]; i++)
      {
        for (var j=0; j<array.shape[1]; j++)
        {
          Console.WriteLine(array[i, j].ToString());
        }
      }
    }
  }
}
```

**Comment by fr0** [comment]
The call to `transpose` is critical to producing the error, so that's probably where the bug is.

**Comment by Oceania2018** [comment]
OK, I'll add it to UnitTest.

**Comment by Nucs** [comment]
This issue should be resolved in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
