### ISSUE TITLE
Upcasting during math operations

### ISSUE THREAD

**Issue by Nucs** [SciSharp/NumSharp#281]
The following code works in python but fails in c#
The backend doesn't handle inconsistent types for example: 
`a+b` where `a` is `double` and `b` is `int` will throw a null reference exception.

Python:
```python
a = np.array([1, 2, 3], dtype=np.float64)
a = a + 1
```
C#:
```C#
var a = np.array(1d, 2d, 3d, 4d, 5d);
var b = a + 1;
```

It can be fixed by detecting that int can be upcasted to double, therefore we can 
apply on `b` `.astype(np.float64)` and then perform the math operation.

**Comment by Nucs** [comment]
Let me know if help needed.

**Comment by Oceania2018** [comment]
Yes, this is needed. You can PR on this.

**Comment by Nucs** [comment]
This issue has been implemented in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
