### ISSUE TITLE
NumSharp's randint functionality differs substantially from NumPy's randint

### ISSUE THREAD

**Issue by Plankton555** [SciSharp/NumSharp#292]
**Description**
I noticed that randint (https://github.com/SciSharp/NumSharp/blob/6c9240f2905436f3cdc12d8d9e8887f72eaa940a/src/NumSharp.Core/Random/np.random.randint.cs) gives completely different results from NumPy's randint. After poking around in NumSharp's source code, [old issues](https://github.com/SciSharp/NumSharp/issues/58), and [NumPy's documentation](https://docs.scipy.org/doc/numpy-1.16.1/reference/generated/numpy.random.randint.html) I think that NumSharp has only been tested for ONE of randint's use cases (namely when all parameters `low, high, shape` are specified). In the other use cases, the behaviour is either completely different from NumPy or exceptions are thrown.

**Minimum example**
```
static void Main(string[] args)
{
    var result_1 = np.random.randint(2, size: 10); // 10 numbers between [2, int.MaxValue)
    var result_2 = np.random.randint(5, size: new Shape(2, 4)); // 8 numbers between [5, int.MaxValue)
    var result_3 = np.random.randint(5, shape: new Shape(2, 4)); // 2x4 matrix with elements between [5, int.MaxValue)
    var result_4 = np.random.randint(low: 0, high: 5); // throws System.NullReferenceException
    var result_5 = np.random.randint(0, 5, null); // throws System.NullReferenceException (equivalent to result_4)
    var result_6 = np.random.randint(5); // Does not even compile
    var result_7 = np.random.randint(low: 0, high: 10, shape: new Shape(2, 2)); // 2x2 matrix with elements between [0, 10)
    var result_8 = np.random.randint(1, 5, 8); // 8 numbers between [1, 5)
    var result_9 = np.random.randint(1, 5, new Shape(3, 2)); // 3x2 matrix with elements between [1, 5)
}
```

**Expected results**
`result_1`: NOT AS EXPECTED - 10 numbers between [0, 2) (this is one of the examples on NumPy's randint documentation)
`result_2`: NOT AS EXPECTED - Either (1) an error since I am passing a Shape to a int parameter, or (2) 8 numbers between [0, 5), or (3) a 2x4 matrix with elements between [0, 5)
`result_3`: NOT AS EXPECTED - 2x4 matrix with elements between [0, 5)
`result_4`: NOT AS EXPECTED - 1 number between [0, 5)
`result_5`: NOT AS EXPECTED - 1 number between [0, 5) (equivalent to result_4)
`result_6`: NOT AS EXPECTED - 1 number between [0, 5)
`result_7`: Expected
`result_8`: Expected
`result_9`: Expected

This is all based on the behaviour of NumPy's randint functionality.

**Versions**
NumSharp version 0.10.3

**Comment by Nucs** [comment]
You are welcome to help us with a PR if you will to.

**Comment by Plankton555** [comment]
Yeah, the thought has struck me. If I get some spare time during the coming days I might as well do that. I'm not that experienced with C# yet but I am very familiar with NumPy, so I guess that could be useful.

**Comment by henon** [comment]
Cool @Plankton555, looks like you would be a very good complement to the NumSharp team. 

By the way, we can migrate the randint test cases from Numpy.NET to NumSharp (and all the others too ultimately).

**Comment by Nucs** [comment]
Thanks for pointing that out @Plankton555.
