### ISSUE TITLE
Implement array cast from integer to double

### ISSUE THREAD

**Issue by Plankton555** [SciSharp/NumSharp#293]
(Sorry for opening so many issues recently, I'm just reporting the problems I am running into while actually trying to port real-world code from Python to C#. I really appreciate the effort you do to implement a C# version of NumPy.)

**Description**
Unable to cast an integer array to a double array. `System.NotImplementedException: '_ChangeTypeOfArray from Int32 to Double'`

**Minimum example**
```
static void Main(string[] args)
{
    NDArray mat = np.arange(4).astype(typeof(double)).reshape(2, 2); // throws exception
}
```

**Expected result**
The array `mat` should contain the corresponding values, but casted to double (`{0.0, 1.0, 2.0, 3.0}`).

**Comment by Nucs** [comment]
This is fixed in an ongoing work on my local branch.
I'll refer to this issue once I finish my work and merge to master.

**Comment by Plankton555** [comment]
Nice, good to hear!

**Comment by Plankton555** [comment]
Would this problem also explain why I get an exception with the following code, or is it a separate problem?

```
static void Main(string[] args)
{
    NDArray output = np.zeros(5);
    double newValDouble = 2;
    int newValInt = 4;
    output[3] = newValDouble; // This works fine
    output[4] = newValInt; // throws System.NullReferenceException

    Debug.WriteLine($"output: {output}");
}
```

That is, assigning an integer to an array containing doubles (as initialized from np.zeros) causes an exception.

**Comment by henon** [comment]
> (Sorry for opening so many issues recently, 
[...]

Never feel sorry. Thank you for opening the issues, by doing that you are contributing to the library in a way!

**Comment by Plankton555** [comment]
> Would this problem also explain why I get an exception with the following code, or is it a separate problem?
>[...]

Running into more problems similar to this, opening a new issue for them for clarity.

**Comment by henon** [comment]
(Sorry for polluting this thread, have no other way of contacting Plankton)

@Plankton555:  Could you try run your ported script against https://github.com/SciSharp/Numpy.NET ? I'd love to know if there are any issues.
