### ISSUE TITLE
NullReferenceException when multiplying scalar with single value from matrix

### ISSUE THREAD

**Issue by Plankton555** [SciSharp/NumSharp#295]
**Description**
I am getting the exception `System.NullReferenceException: 'Object reference not set to an instance of an object.'` when I extract a single value from 2-d array and multiply it with a scalar. My guess is that there's some combination of multiplication with different data types that is not defined/implemented or something.

**Minimum example**
```
static void Main(string[] args)
{
    NDArray mat = new double[,] { {1.0, 2.0 }, {3.0, 4.0 } };
    var singleVal = np.sqrt(mat[1, 0] + mat[1, 1]); // sqrt(7.0) = ~2.646
    var result = 15 * singleVal; // 15 * 2.646 should be ~39.686, but throws System.NullReferenceException
}
```

**Expected result**
The variable `result` should be roughly 39.686 (`15 * sqrt(7)`).

**Comment by Plankton555** [comment]
The problem seems to never occur when `singleVal` is declared as a double instead of a var.

**Comment by Nucs** [comment]
The problem lies in Default.Multiply as no upcasting is implemented yet.
Related to #281 and to the ongoing rewriting of the backend.

**Comment by Nucs** [comment]
This issue should be resolved in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
If it persists, Reopen the issue let us know please.
