### ISSUE TITLE
Multiplying double array with "castable non-doubles" throws exception

### ISSUE THREAD

**Issue by Plankton555** [SciSharp/NumSharp#296]
**Description**
Types such as int or float are normally "automatically" casted to double if needed. However, when multiplying a `double` array with an `int` or `float`, a `NullReferenceException` is thrown. The same kind of problem seems to happen when a "castable non-double" is assigned as an element in a double array.

**Minimal example**
```
static void Main(string[] args)
{
    NDArray arr = np.random.rand(2, 2);
    // Debug.WriteLine($"{arr}");

    double myDouble = 5;
    NDArray result_d = arr * myDouble; // works just fine

    float myFloat = 5;
    NDArray result_f = arr * myFloat; // throws System.NullReferenceException

    int myInt = 5;
    NDArray result_i = arr * myInt; // throws System.NullReferenceException

    // Debug.WriteLine($"{result_f}");
    // Debug.WriteLine($"{result_d}");
}
```

**Expected result**
It should be possible to multiply `arr` with 5, no matter if the 5 is declared as a `double`, `float`, or `int`.

**Comment by Nucs** [comment]
Related to #281 and is a WIP by me.

**Comment by Nucs** [comment]
This issue has been resolved in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
If it persists, Reopen the issue let us know please.
