### ISSUE TITLE
Implement numpy.mean

### ISSUE THREAD

**Issue by Plankton555** [SciSharp/NumSharp#297]
Compute the arithmetic mean along the specified axis.

NumPy docs: https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html

Corresponding NumSharp class: https://github.com/SciSharp/NumSharp/blob/master/src/NumSharp.Core/Statistics/NDArray.mean.cs

**Comment by Nucs** [comment]
This issue has been implemented in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
