### ISSUE TITLE
Dropping implementation of IStorage and TypedArrayStorage  

### ISSUE THREAD

**Issue by Nucs** [SciSharp/NumSharp#311]
#### Proposition
Drop `IStorage` and `TypedArrayStorage` in favor of performance increase and `UnmanagedByteStorage`.

1. When using an interface explictly (like in the following example), the overhead of virtual tables causes methods that are called recusivly and/or a lot like `GetValue`, `GetIndexor` or `SetValue` to be slower.
A single virtual-call is equal to 10 direct method calls (see: [ViaInterface_*](https://gist.github.com/Nucs/3a26028381ff8b09b747797ff13d6285)).

```C#
    IStorage storage = new TypedArrayStorage();
    for (int i = 0; i < 100_000; i++)
        storage.GetValue(i); 
    }

    //10 ops less every iteration:
    TypedArrayStorage storage2 = new TypedArrayStorage();
    for (int i = 0; i < 100_000; i++)
        storage2.GetValue(i); 
    }
```
2. An entire new backend was written (`Unmanaged`) for `UnmanagedByteStorage` which uses only unsafe code and is incompatible with current `DefaultEngine` unless we pin the array inside `TypedArrayStorage` via `GCHandle.Alloc(array, GCHandleType.Pinned)` to gain access to the storage's array address.
This is exactly what is done inside `UnmanagedByteStorage` initialization, therefore we do not need `TypedArrayStorage`.
All methods inside current `DefaultEngine` will be/were rewritten to use pointers which gave a significant performance improvement but as mentioned, made it incompatible with `TypedArrayStorage` because it provides no pointer.

3. If we will implement any external library - we'll just implement a different engine that'll customize all functions and still use `UnmanagedByteStorage` as the memory storage.
If CUDA provides us with their own PTR to the GPU's memory, we can still use `UnmanagedByteStorage` as long as the cuda-backend-engine will have to know that they are limited to certain actions.
4. Using `IStorage` prevents the compiler from optimizing `[MethodImpl(MethodImplOptions.AggressiveInline)]` which is a serious performance booster.

#### Proposition 2
`ITensorEngine` will turn into `abstract class TensorEngine`.
Abstract is faster than using an interface.
see: [this benchmarks](https://gist.github.com/Nucs/3a26028381ff8b09b747797ff13d6285).

**Comment by Nucs** [comment]
Related to #301

**Comment by henon** [comment]
I see no reasons not to but I don't know the library as deeply as Haiping.

**Comment by Nucs** [comment]
This issue has been resolved in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
