### ISSUE TITLE
Negative slice error

### ISSUE THREAD

**Issue by 134579** [SciSharp/NumSharp#312]
hi, I see from [wiki](https://github.com/SciSharp/NumSharp/wiki/Slice-Notation)
 that slice start and stop can be negative number, but the following test case doesn't pass
```      
        [TestMethod]
        public void Slice_Neg()
        {
            var x = np.arange(5);
            var y = x["-2:"];
            AssertAreEqual(new int[] {3, 4}, y.Data<int>());
        }
```
error:

```
NumSharp.UnitTest.Selection.IndexingTest.Slice_Neg

Assert.AreEqual failed. Expected:<2>. Actual:<5>. Arrays are not of same length. Expected'2', given '5'
```
and the resulting y equals 
```array([0, 1, 2, 3, 4])```

**Comment by henon** [comment]
I remember negative values in slice notation have been added a while ago (not by me though, when I implemented slicing I forgot about them). I think it was kathdi. Maybe not all cases have been covered. 

Right now, we are refactoring the library for better performance, so it is a bad time to fix this. Can you try to calculate positive values for the slicing notation yourself in the meanwhile?

When I reimplement slicing for the new unmanaged NDArray I'll not forget about the negative indices this time.

**Comment by 134579** [comment]
OK
