### ISSUE TITLE
mgrid gives bad second result

### ISSUE THREAD

**Issue by JetstreamRoySprowl** [SciSharp/NumSharp#313]
The mgrid function returns two identical arrays, while [the spec says](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mgrid.html) that (for square arrays at least) the second return value should be the transpose of the first.

The unit test for mgrid demonstrates this error.

**Comment by JetstreamRoySprowl** [comment]
I've found several other errors besides this one, and I'm glad to do a PR for them all. Can you give me any idea how long it might take to get the PR taken?

**Comment by Nucs** [comment]
We will gladly accept contributions, as soon as you pull request, we'll review and merge.
