### ISSUE TITLE
just starting with numsharp and I don't understand the syntax

### ISSUE THREAD

**Issue by thomasd3** [SciSharp/NumSharp#316]
In Python:
```
import numpy as np

a = np.arange(100)
b = a[20:50]
```

no problem..

with NumSharp:

```
var a = np.arange(100);
var b = a[20, 50];

```
I get an out of bounds error (while a.len returns 100)

What am I missing?

**Comment by Nucs** [comment]
You are trying to perform a slice, all items between 20 to 50 (`[20:50]`)
What you are actually doing is access index `[20,50]` of a shape `(20+, 50+)`
What you need to do is `var b = a["20:50"];`

**Comment by thomasd3** [comment]
ok, I get it! but is there a faster way where I can access slices with variables? in my case I have a lot of sliding windows across data, so making a string to decode it right after is not going to be very fast.

**Comment by Nucs** [comment]
Yes,
`a[new Slice(20, 50)]`

> Additionally, how can I get a single value from its index?

`nd.GetDouble(22,15)` or any similar Get methods of that sort (depending on your dtype).

**Comment by Oceania2018** [comment]
@Nucs Do you have plant to add function`NDArray GetNDArray(1)` to get specific dimension data (Scalar or NDArray). or you can write a generic function `T Get<T>(params int[] dims)`.

**Comment by Nucs** [comment]
In my branch I have them both iirc,
`this[int[]]` returns a `NDArray` - handles all shapes, doesn't copy.
`GetAtIndex(int)` - Get at specific linear offset
`Get<T>`, `GetInt32`, `GetTYPE` - handle scalar return, all take in `int[]`

Same set for setters.

**Comment by Nucs** [comment]
If there are any topic related questions, please reopen this issue.
