### ISSUE TITLE
Target for this project

### ISSUE THREAD

**Issue by thomasd3** [SciSharp/NumSharp#317]
Is the goal of NumSharp to be a 1:1 port of numpy?

Or is the goal to be compatible with numpy but eventually have other extra features?

**Comment by henon** [comment]
it is a subset of numpy with compatible interface.

if you want all of the original check out this: https://github.com/SciSharp/Numpy.NET

**Comment by Nucs** [comment]
NumSharp aims to be as identical as possible with numpy,
At this current time, [Numpy.NET](https://github.com/SciSharp/Numpy.NET) has a better, more reliable and more coverage of numpy's features **but** it does requires you to have python installed.

**Comment by Nucs** [comment]
If there are any topic related questions, please reopen this issue.

**Comment by Oceania2018** [comment]
v0.11.0 changed a lot compared to v0.10.0 due to performance improvement.
