### ISSUE TITLE
Not understanding the standard deviation

### ISSUE THREAD

**Issue by thomasd3** [SciSharp/NumSharp#318]
In Python:

```
a = np.array([ 1, 1, 2, 4, 1, 1 ])
b = np.std(a)
```

the output is: 1.1055415967851332

with numsharp:

```
var a = new NDArray(new[] { 1, 1, 2, 4, 1, 1 });
var b = a.std();
```

the output is: 2.88675134594813

what am I missing?

**Comment by Nucs** [comment]
This issue has been resolved in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
If it persists, Reopen the issue let us know please.
