### ISSUE TITLE
np.argmax with axis

### ISSUE THREAD

**Issue by acanus** [SciSharp/NumSharp#319]
The np.argmax with axis =2 always return zero array.

**Comment by Nucs** [comment]
This issue has been fixed in [branch](https://github.com/SciSharp/NumSharp/tree/unmanaged-bytes-storage) and will be merged to master in couple of days

**Comment by Nucs** [comment]
This issue has been resolved in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
If it persists, Reopen the issue let us know please.
