### ISSUE TITLE
Get rid of the NDArray.order

### ISSUE THREAD

**Issue by JetstreamRoySprowl** [SciSharp/NumSharp#322]
How much resistance would there be to getting rid of the `order` property from Shape and NDArray? The `order` concept is used as a parameter for reshape in Python, but it does not seem to exist in Python as a member at all. 

The reason I ask is because I've had to implement a bunch of functionality that allows efficient arbitrary dimensionality in several of the operations, and I'd love to provide this as a pull request. The reason I can't is because the `order` property means that every matrix operation would have to be implemented in at least two different ways and maybe four. 

I've got a bunch of efficient code here that I can't offer you because of `order`, and I'm sure it will continue to defeat optimization attempts in the future.

BTW, I will do the work required to get rid of it if I'm allowed to. All that's needed is to re-implement transpose properly.

**Comment by Nucs** [comment]
Following our private discussion, in the [new branch](https://github.com/SciSharp/NumSharp/tree/unmanaged-bytes-storage) we do not support transpose (currently) and will not support `order` for a while so it is safe to stick to 'C' order.

**Comment by Oceania2018** [comment]
I think we don’t have to implement them for all, if you have checked how we handle order currently, you will know the order is transparent to logic computation layer. Storage layer is responsible for getting a piece of data, no matter what the order is.

**Comment by Nucs** [comment]
As we released the changes, `order` is no longer used in NumSharp.
