### ISSUE TITLE
np.std error result

### ISSUE THREAD

**Issue by 134579** [SciSharp/NumSharp#325]
```
        void test_standard_deviation() {
            var array = np.array(new double[] {1});

            NDArray std = array.std();

            Assert.Equal(0, std.GetDouble());
        }
```
failed

**Comment by Nucs** [comment]
This issue has been resolved in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
If it persists, let me know please.
