### ISSUE TITLE
Need NuGet pre-release for unmanaged-bytes-storage

### ISSUE THREAD

**Issue by JetstreamRoySprowl** [SciSharp/NumSharp#333]
@Oceania2018 I've just finished a project which I've converted from NumSharp 0.10.4.0 to the unmanaged-bytes-storage branch per a suggestion from @Nucs. Unfortunately for me, the project needs to run in Docker containers, which means I really need a NuGet package. Would it be possible to get a NuGet pre-release for unmanaged-bytes-storage in the next day or two?

**Comment by Nucs** [comment]
@Oceania2018 I'll contact you once we merge to master to release it as a pre-release.

**Comment by Oceania2018** [comment]
Once you merged, I'll release an alpha version. A big milestone.

**Comment by Oceania2018** [comment]
@JetstreamRoySprowl Released: https://www.nuget.org/packages/NumSharp/0.11.0-alpha

Follow us on Twitter, keep up to date: https://mobile.twitter.com/ScisharpS

**Comment by JetstreamRoySprowl** [comment]
Thank you, and congratulations!! @Oceania2018  @Nucs
