### ISSUE TITLE
np.prod([1]) should return a Scalar

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#334]
Python:
![image](https://user-images.githubusercontent.com/1705364/62507442-0532c180-b7ca-11e9-982d-324243a65c0b.png)

NumSharp-v0.10.x:
![image](https://user-images.githubusercontent.com/1705364/62507455-15e33780-b7ca-11e9-98af-2e574b1c287f.png)

NumSharp-umanaged-storage:
![image](https://user-images.githubusercontent.com/1705364/62507516-4f1ba780-b7ca-11e9-9816-bf45e5bedb93.png)

![image](https://user-images.githubusercontent.com/1705364/62507570-8427fa00-b7ca-11e9-9eb0-4acb09451e8d.png)

**Comment by Nucs** [comment]
Fixed in unmanaged-bytes-storage branch
