### ISSUE TITLE
Addition throws ArgumentNullException exception in 0.11.0-alpha2

### ISSUE THREAD

**Issue by JetstreamRoySprowl** [SciSharp/NumSharp#338]
This throws an ArgumentNullException:

            var fff = new float[] { 1.0F };
            var xxx = new NDArray(fff);
            var zzz = xxx + 1;  // throws ArgumentNullException

Lengths > 1 seem to work fine:

            var fff = new float[] { 1.0F, 1.0F };
            var xxx = new NDArray(fff);
            var zzz = xxx + 1;   // okay

**Comment by Nucs** [comment]
It was an issue the computation of Shape's hashcode when they are initialized with an empty array.
Thanks, fixed in referenced commit above.
