### ISSUE TITLE
np.multiply is extremly slow

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#339]
Run TensorFlow.NET Logistic Regression:

![image](https://user-images.githubusercontent.com/1705364/62667609-11478c00-b94e-11e9-9fa1-891004ad91dd.png)

**Comment by Nucs** [comment]
A. You can not evaluate execution speed with visual studios line execution counter.
B. The library is not built to be used in a `DEBUG` configuration. It heavily relies on JIT optimization and aggressive inlining which occurs **only** when run in a `RELEASE` config or compiled with:
![image](https://user-images.githubusercontent.com/649919/62683368-ebaa9900-b9c6-11e9-98bc-3e7b0d0204e6.png)

**Comment by Oceania2018** [comment]
I use release mode and optimize code.
It's better, but still slower than before.

![image](https://user-images.githubusercontent.com/1705364/62697229-e1c16f80-b99f-11e9-8b19-65e35aac96b8.png)

**Comment by Oceania2018** [comment]
I've pushed debug code to https://github.com/SciSharp/TensorFlow.NET/tree/numsharp-unmanaged-storage.

Run Example project as:
![image](https://user-images.githubusercontent.com/1705364/62698231-41b91580-b9a2-11e9-83bc-e712f1248c46.png)

Please compare it with previous version. I really hope there is not performance regression.

**Comment by Oceania2018** [comment]
It's better now.
The first iteration needs JIT optimization. After that, it's more faster than before.

![image](https://user-images.githubusercontent.com/1705364/62840531-ef0d8100-bc61-11e9-97e2-14816be70a2f.png)

**Comment by Nucs** [comment]
As `np.multiply` and all ops were optimized to as far as possible, I see the issue resolved.
As for `session.run`, it is a mix of functions - I'll see what I can do.
