### ISSUE TITLE
Support 4th dimension slice

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#342]
When I pass `":, :, :, :, 0:2"` to `new Slice()`, throw exception.

![image](https://user-images.githubusercontent.com/1705364/64067945-37cbb080-cbf6-11e9-99af-0542c937334e.png)

![image](https://user-images.githubusercontent.com/1705364/64067942-25ea0d80-cbf6-11e9-8064-3436dc3cdfe7.png)

**Comment by henon** [comment]
what was the cause of the exception? why is it closed?

**Comment by henon** [comment]
Oh, I see now. In case anyone hits a similar error in the future:

The `Slice` object only represents the slicing of a single dimension. A multidimensional slice notation is parsed into a `Slice[]` by calling the static method `Slice.ParseSlices( ":, :, :, 0:2")`

**Comment by Oceania2018** [comment]
@henon Yes, you're right. I use `Tensor this[params Slice[] slices]{ }`, it works.
