### ISSUE TITLE
np.Transpose doesn't work when it is square matrix.

### ISSUE THREAD

**Issue by KIMGEONUNG** [SciSharp/NumSharp#346]
np.Transpose doesn't work when it is square matrix. The transpose for square matrix always return the original matrix. 
For example, [[1,2],[3,4]] -->  [[1,2],[3,4]]

**Comment by Nucs** [comment]
We do not have transpose implemented for n-dimensions therefore np.transpose does not work yet.

Duplicate issue #117.

**Comment by Nucs** [comment]
`np.swapaxes`, `np.transpose`, `np.moveaxis` and `np.rollaxis` were added in the [this commit](https://github.com/SciSharp/NumSharp/commit/39896599ac40584821802cfd63a15458060289ba ).
And will be released soon in 0.20.4.
