### ISSUE TITLE
Is it possible to use NumSharp in Unity?

### ISSUE THREAD

**Issue by guoguoguilai** [SciSharp/NumSharp#353]
When I import NumSharp in Unity, it throw two errors:
(1) Assembly 'Library/ScriptAssemblies/Assembly-CSharp.dll' will not be loaded due to errors:
Reference has errors 'NumSharp.Core'.
(2) Assembly 'Assets/Packages/NumSharp.0.20.3/lib/netstandard2.0/NumSharp.Core.dll' will not be loaded due to errors:
Unable to resolve reference 'System.Runtime.CompilerServices.Unsafe'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'System.Memory'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.

So how can I solve this?

**Comment by Nucs** [comment]
It should be possible, it seems that the nuget references that NumSharp has are not packaged/loaded along with NumSharp.
Install them individually:
These can be found at [NumSharp.Core.csproj](https://github.com/SciSharp/NumSharp/blob/master/src/NumSharp.Core/NumSharp.Core.csproj#L132)
> `<PackageReference Include="System.Memory" Version="4.5.3" />`
> `<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.2" />`

**Comment by Nucs** [comment]
Has this resolved your issue?

**Comment by guoguoguilai** [comment]
> Has this resolved your issue?

Yeah. It works. Thank you so much!

**Comment by TardiCoder** [comment]
By any chance could you specify the steps? I am having trouble installing NumSharp to Unity. Thanks!

**Comment by Nucs** [comment]
@TardiCoder If I remember correctly, You have to make sure the `NumSharp.dll` to be in the same folder as your compiled script.

**Comment by TardiCoder** [comment]
Thank you sooo much! BTW I love your name!

**Comment by TardiCoder** [comment]
Should I look in my project folder for the dlls? Thanks! Sorry for the delayed responding. I am only 12 and newish to C#. Thanks you for everything.

**Comment by Nucs** [comment]
Yes, look for them at: `YourProjectName\bin\Debug` (Debug might be Release, depending on your build)

**Comment by TardiCoder** [comment]
Yeah, they aren't there. My project isn't complete, though. I needed to use NumSharp for that activation function in my AI. I understand I will be able to continue development after I build, but my project wouldn't work. Should I plug in all the methods, even if they cause errors, and let the methods fix when I build the project?

**Comment by Nucs** [comment]
DM me in our [gitter](https://gitter.im/sci-sharp/community) and I'll help you out

**Comment by TardiCoder** [comment]
Ok thanks! It'll be a while before I can do that because I have a thing to do. Thank you for all your 1 on 1 help!

**Comment by lance-lot** [comment]
I'm also trying to run numsharp in unity and I have followed the steps which @Nucs  said, but I 've got another eeror 
'IL2CPP error for type 'NumSharp.LAPACKProviderType' in assembly '/Users/yc/Downloads/tf-lite-unity-sample/Temp/StagingArea/Data/Managed/NumSharp.Core.dll'
Additional information: Value of type 'int' is too large to convert to ushort.'
Any help please? 
![截屏2020-04-07 下午9 28 45](https://user-images.githubusercontent.com/52097228/78678974-38f75580-791c-11ea-8688-4aa3dd5deacf.png)

**Comment by bth5032** [comment]
Hey, I'm actually also having trouble following this and the aforementioned [blog post](https://medium.com/@jonfoust/using-gcp-nuget-packages-with-unity-8dbd29c42cc4) as a C# noob. Could we get some more explicit instructions? 

For the uninitiated like me, I've managed to get part way there (will update with full instructions if I get it working):

First, the `dll` files you need are one directory level above your Unity Assets folder in a directory called `Packages`. In there, you will find a bunch of packages, including some extra you didn't install which are probably there by defualt.  I just went through each of them and if they had a named `.dll` inside a directory called `/lib/netstandard2.0/`, I copied that into `Assets/Plugins/`. That lines up with @Nucs ' comment. 

The blog post included a discussion about adding a `link.xml` file inside the project directory too (one level above 'Assets'). I have a feeling I'm stuck there. So far the link file I made looks like this

```xml
<?xml version="1.0" encoding="utf-8"?>

<linker>
  <assembly fullname="NumSharp">
    <type fullname="NumSharp" preserve="all"/>
  </assembly>
</linker>
```

but this doesn't seem to work. The blog post claims you need to do this for each lib, but I'm not sure what `fullname` in each of the rows should befor each of the three libs (NumSharp, System.Memory, System.Runtime.CompilerServices.Unsafe).

Thanks very much for the help, sorry to resurrect a thread, but just would like this to have a complete answer for me and the next guy.

**Comment by sci-comp** [comment]
> Hey, I'm actually also having trouble ...

Hi, For Unity, NumSharp had three dependencies when I tried it,

https://www.nuget.org/packages/System.Buffers/
https://www.nuget.org/packages/System.Memory/
https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/

To install, download the package, extract (7zip is nice), then copy the .dll file located in ./lib/netstandard2.0/ into YourUnityProject/Assets/Plugins/

Good luck!

**Comment by julia-koziel** [comment]
> I'm also trying to run numsharp in unity and I have followed the steps which @Nucs said, but I 've got another eeror
> 'IL2CPP error for type 'NumSharp.LAPACKProviderType' in assembly '/Users/yc/Downloads/tf-lite-unity-sample/Temp/StagingArea/Data/Managed/NumSharp.Core.dll'
> Additional information: Value of type 'int' is too large to convert to ushort.'
> Any help please?
> ![截屏2020-04-07 下午9 28 45](https://user-images.githubusercontent.com/52097228/78678974-38f75580-791c-11ea-8688-4aa3dd5deacf.png)

Hi, did you manage to resolve this issue? NumSharp is running smoothly in Unity for me, but I receive the same error "Value of  type 'int' is too large to convert to ushort" when building.
