### ISSUE TITLE
nd[np.newaxis, :]

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#355]
Can we support `nd[np.newaxis, :]` and `nd[:, np.newaxis]` ?

![image](https://user-images.githubusercontent.com/1705364/66179033-fd0dcb80-e62c-11e9-8b0f-4acd7d5f8426.png)

**Comment by Nucs** [comment]
Duplicate of https://github.com/SciSharp/NumSharp/issues/344.

**Comment by Nucs** [comment]
Untill then:
`nd[np.newaxis, :] == np.expand_dim(nd, 0)`
`nd[:, np.newaxis] == np.expand_dim(nd, -1)`

**Comment by Oceania2018** [comment]
Cool

**Comment by henon** [comment]
I just implemented it in PR https://github.com/SciSharp/NumSharp/pull/357
