### ISSUE TITLE
Can't Install NumSharp from Visual Studio 2013 nuget

### ISSUE THREAD

**Issue by yeohseong** [SciSharp/NumSharp#370]
![image](https://user-images.githubusercontent.com/57782114/69947711-2eb9ea80-1529-11ea-98e7-9b7bf05a1438.png)
![image](https://user-images.githubusercontent.com/57782114/69947744-45604180-1529-11ea-959a-0151dc4cd92d.png)
![image](https://user-images.githubusercontent.com/57782114/69947781-5610b780-1529-11ea-88be-d67831129ed4.png)
![image](https://user-images.githubusercontent.com/57782114/69947804-63c63d00-1529-11ea-9a32-f4e89773b0d0.png)

Please help !!!!! Facing this problem around 3 days.

Thank

**Comment by Nucs** [comment]
Hey, I think it has to do with the fact that NumSharp is targeting `.netstandard 2.0` which makes me wonder if it is supported by VS 2013.
Also your current project is targeting `.net framework 4.7.1` and if the VS has no understanding of `.netstandard`, it wont be able to bind it as `.net4.7.1`.

I suggest you to upgrade to [2019's community version](https://visualstudio.microsoft.com/downloads/) which is entirely free and provides really all you need.

**Comment by Nucs** [comment]
As said in [this comment](https://github.com/dotnet/standard/issues/241#issuecomment-286904570):
> VS 2015 had some minimal support for .NET Standard projects via the old PCL projects, however the recommended projects are base .NET Core tooling that ships only with VS2017 so yes in order to create .NET Standard libraries it would require VS2017. You will be able to consume one in earlier version of VS but not produce one.

Therefore NumSharp can be installed on VS2017 and beyond as all nuget packages targeting .netstandard.

**Comment by yeohseong** [comment]
Thank for reply.
any method to install it at VS2013?

**Comment by Nucs** [comment]
@yeohseong, Please try the following solution:
https://stackoverflow.com/a/44648397/1481186

**Comment by yeohseong** [comment]
Is this .net C#? or Html? Because I am new in Programming :)

Thank

**Comment by Nucs** [comment]
Actually nevermind, the solution I gave you won't work.
I don't really have a suggestion on how to fix it except to upgrade to a new visual studio version.
