### ISSUE TITLE
np.where is expected !

### ISSUE THREAD

**Issue by AvenSun** [SciSharp/NumSharp#376]
Hi,guys
NumSharp is great!
recently I'm trying porting some python code to c#, 
and I found there's no support of np.where,
I also noticed some issues about this problems ( #78 ,#362 )
actually there're a lot usages between pre-processing and post-processing,
though we can do it via loops, it's low performance. 
is there a deadline or plan on this ?
thx!

**Comment by Nucs** [comment]
Within a week I'll finish it.

**Comment by Oceania2018** [comment]
@AvenSun I've been waiting the feature for two months as well.
I believe @Nucs will make it happen, big surprise for us.

**Comment by AvenSun** [comment]
@Nucs 
It'll be a great news to all SciSharp fans.
looking forward to the PR.

**Comment by RileyGe** [comment]
This function is finished or not?

**Comment by jacke-holmes** [comment]
is this expected?

**Comment by AlizerUncaged** [comment]
any news on this?
