### ISSUE TITLE
System.MissingMethodException: 'Method not found'

### ISSUE THREAD

**Issue by masoudnick** [SciSharp/NumSharp#394]
Hi,
I wrote an ocr program with Tensorflow.Net and NumSharp.At runtime i am facing an error in 32 line.
`System.MissingMethodException: 'Method not found: 'NumSharp.NDArray NumSharp.NDArray.get_Item(NumSharp.NDArray[])'.'
`
How can i fix this?

![Capture23](https://user-images.githubusercontent.com/20556982/73611135-f3ed3500-45f3-11ea-8cdf-fa252c4866f9.JPG)

**Comment by Nucs** [comment]
This issue is on TF.NET's dependency on NumSharp. try to upgrade NumSharp or downgrade it.

**Comment by masoudnick** [comment]
@Nucs 
Thanks,i upgraded NumSharp to 0.20.5 version. that error fixed.
But why lines 34,35 have `Specified method is not supported` error?!!!!
Are `np.squeeze` and `np.argmax` changed in new version?
