### ISSUE TITLE
The type 'NDArray' exists in both 'NumSharp.Core

### ISSUE THREAD

**Issue by Mghobadid** [SciSharp/NumSharp#399]
after update package i faced with this error 
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'NDArray' exists in both 'NumSharp.Core, Version=0.20.4.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'NumSharp.Lite, Version=0.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'	WpfApp1	H:\xxxx\xxx\MainWindow.xaml.cs	135	Active
`

**Comment by Oceania2018** [comment]
What libraries are you using?

**Comment by Mghobadid** [comment]
i use this libraries 
NumSharp => 0.20.5
SciSharp.TensorFlow.Redist =>1.15.0
SharpCV =>0.40
TensorFlow.NET =>0.14.2

**Comment by Oceania2018** [comment]
You can downgrade SharpCV to 0.3.2.

**Comment by pavelsavara** [comment]
This problem shows again when you want to use
https://www.nuget.org/packages/TensorFlow.NET/0.15.1
together with 
https://www.nuget.org/packages/NumSharp/0.20.5

Any advice ?
