### ISSUE TITLE
installation error on VS2019 windows 10

### ISSUE THREAD

**Issue by wendongwangmpi** [SciSharp/NumSharp#403]
I tried to install NumSharp on VS2017 community and VS2019 community on a windows 10 computer, but the following error occurred. 

"Could not install package 'NumSharp 0.20.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

A screenshot is in the link below: 
https://www.dropbox.com/s/ivioijssauzsaqn/screenshot.JPG

**Comment by Nucs** [comment]
NumSharp targets netstandard2.0 which supports net-framework 4.6.2 and above. You'll have to change your project target to .net frame 4.6.2 or above. Even would be to move to netcore.
