### ISSUE TITLE
Is there any computation speed comparision between NumSharp and numpy ?

### ISSUE THREAD

**Issue by quant-science** [SciSharp/NumSharp#431]
Is there any computation speed comparision between NumSharp and numpy ?

**Comment by Nucs** [comment]
Hey, unfortunately we do not have recorded benchmarks. During development I did do benchmarks and numpy always beat NumSharp by being at-least 50% faster in most of the cases. If you are targeting trading with it (time-critical computation) then I suggest you either try [Numpy.NET](https://github.com/SciSharp/Numpy.NET) or numpy on python.
