### ISSUE TITLE
System.NotSupportedException: 'Unable to broadcast already broadcasted shape.'

### ISSUE THREAD

**Issue by minhduc66532** [SciSharp/NumSharp#442]
Here is the code 
```
var shape = Z.shape;
var (u, v) = np.meshgrid(np.arange(shape[1]), np.arange(shape[0]));
var x = (u - Cu) * Z / f; <--- error raised here
var y = (v - Cv) * Z / f;
return np.vstack(x.ravel(), y.ravel(), Z.ravel());
```
![image](https://user-images.githubusercontent.com/66398066/109139366-094c7880-778e-11eb-8855-e4a4e0458145.png)
Any ideas ?

**Comment by Nucs** [comment]
We do not support broadcasting an already broadcasted NDArray.
My guess is the meshgrid uses broadcasting. If you'll clone the NDArray (`NDArray.Clone()`) that'll produce a linear/contagious stored NDArray which then can be broadcasted again.

**Comment by minhduc66532** [comment]
My solution currently is to use np.full like this

```
var shape = Z.shape;
var (u, v) = np.meshgrid(np.arange(shape[1]), np.arange(shape[0]));
var CU = np.full(Cu, shape[0], shape[1]);
var CV = np.full(Cv, shape[0], shape[1]);
var x = (u - CU) * Z / f; 
var y = (v - CV) * Z / f;
return np.vstack(x.ravel(), y.ravel(), Z.ravel());
```
