### ISSUE TITLE
implement eye 

### ISSUE THREAD

**Issue by dotChris90** [SciSharp/NumSharp#46]
implementing numpys eye method following https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html?highlight=eye#numpy.eye

**Comment by dotChris90** [comment]
ok did now but just for 2D so I keep issue open.

**Comment by Nucs** [comment]
This issue has been implemented in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
