### ISSUE TITLE
numpy.cross missing in the API

### ISSUE THREAD

**Issue by guptaanmol184** [SciSharp/NumSharp#478]
Hi,

I am unable to find [numpy.cross](https://numpy.org/doc/stable/reference/generated/numpy.cross.html) in the API? If it is not available, what might be the best workaround?

**Comment by ChengYen-Tang** [comment]
I found a more complete package, maybe you can try it.
https://github.com/Quansight-Labs/numpy.net

**Comment by guptaanmol184** [comment]
Thanks for the info @ChengYen-Tang, That works for my use case! Closing the issue for now.
