### ISSUE TITLE
Implement a method which computes .NET tensor from NDArray

### ISSUE THREAD

**Issue by dotChris90** [SciSharp/NumSharp#52]
I was thinking that it could be very beneficial to create a method "ToDotNetArray" which convert the 1D NDArray to a jagged array in .NET World. 

- Name --> ToDotNetArray
- Input --> nothing
- output --> dynamic 

The reason for this is "better integration of NumSharp for other .NET packages". So no Numpy based reason for implementation.

**Comment by Oceania2018** [comment]
Agree with you.

**Comment by dotChris90** [comment]
ok will do ;)

**Comment by Oceania2018** [comment]
Why not use `public T[] ToDotNetArray<T[]>()` for 1-d, `public T[][] ToDotNetArray<T[][]>()` for 2-d?

**Comment by dotChris90** [comment]
adapted the interfaces (input parameter and output value). 
Used Jagged Arrays because this is the more general array and better performance. 
Anyway still not general enough - so keep issue open ;)

**Comment by Nucs** [comment]
These methods already exist and were rewritten by me.
