### ISSUE TITLE
Is NumSharp valuable to move forward?

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#55]

**Comment by dotChris90** [comment]
Definitely. I think it has great potential. Not just for C#. But for many languages

**Comment by fdncred** [comment]
Agreed

**Comment by vunb** [comment]
Without NumSharp i only think of Python to write a machine learning project but while i am familiar with C#. From now, this is good point to start a new ML project with C# dotnet. Thank you all!

**Comment by geffzhang** [comment]
https://github.com/dotnet/machinelearning/pull/1517/files/6ef3d151542a294769760d39821b032d61f579c7#diff-98600d2dd295f74940385be2452a8b8c 
Python environments. NimbusML provides Python APIs to ML.NET and easily
integrates into [Scikit-Learn](http://scikit-learn.org/stable/)

**Comment by Oceania2018** [comment]
@geffzhang It's still python. We can reference it. Thanks for your information.

**Comment by dotChris90** [comment]
@geffzhang the goal of NumSharp is to create an Numpy like framework. :)

If we want to integrate python code to dotnet, we would go with Iron python. This project is a c# based python interpreter.

On top I think it is a good software training and project to have fun. :)

But thanks for the link.

**Comment by Oceania2018** [comment]
Positive response.
