### ISSUE TITLE
Implement NDArray.ToString()

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#60]
Create this issue to keep improving string formatting for multiple dimension array.

@dotChris90 I really like this format. Appreciate.

![image](https://user-images.githubusercontent.com/1705364/47999335-eb900c80-e0c7-11e8-8f47-44959c3f6839.png)

**Comment by dotChris90** [comment]
yeah thanks - but there is still some format stuff I have to fix. Maybe will do all together. 
If I create double array - the format looks quite ugly still.

**Comment by Oceania2018** [comment]
@dotChris90 When you push code, please reference `# ISSUE_NUMBER` on the comment. Github will connect the commit with according issue automatically.

**Comment by dotChris90** [comment]
Ok will follow from now

**Comment by Oceania2018** [comment]
@dotChris90 Could you check it now, it seems like doesn't work due to refactor. Thanks.

**Comment by dotChris90** [comment]
yeah will do

**Comment by henon** [comment]
stale issue
