### ISSUE TITLE
Release notes and tracking

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#65]
We have released v0.6.

![image](https://user-images.githubusercontent.com/1705364/50405980-37833780-0782-11e9-961c-7ae3f0368d0c.png)

@dotChris90 , @fdncred , @AoaAquarius and @Esther2013  Thanks all of you. Your excellent job make the NumSharp more and more closer to its goal.

**Comment by Oceania2018** [comment]
### v0.4 release planning Dec 1st, 2018
#### changes:
* Performance improved for np.arange.
* Added axis support for np.amin.
* Separate PowerShell extension project.
* Remove all dynamic variable.
* Added benchmark project.

@dotChris90 @fdncred @Esther2013 @AoaAquarius @PppBr Please add more if you come up ideas.

**Comment by Oceania2018** [comment]
### NumSharp v0.5 release planning Jan 1st, 2019
#### changes:

* Updated online documents.

@dotChris90 @fdncred @Esther2013 @AoaAquarius @PppBr @vunb @KevinMa0207 @tatadyj  Please add more if you come up ideas.

**Comment by Oceania2018** [comment]
NumSharp v0.6 release planning Feb 1st, 2019
Key changes:

**Comment by Oceania2018** [comment]
NumSharp v0.7 release planning March 1st, 2019

#### Key changes:
* Docs enhanced.

**Comment by Nucs** [comment]
This will be moved to a wiki page.
