### ISSUE TITLE
Which interfaces a NArray shall implement?

### ISSUE THREAD

**Issue by dotChris90** [SciSharp/NumSharp#66]
Hello NumSharp fans, 

Since all great collections of numeric values implement some interfaces, I was thinking which we shall target?

It is not a critical question but it come to my mind and want to ask the others of you 

- IEnumerable< T > --> would be fine since we store all numerics in one 1D array (so should be not to hard to implement)
- IList< T > --> because indexing but as far as I was reading IList< T > forces you to implement indexing with one int (which bring me to the question "ok what about matrix or Tensor? if we use a single int shall it be splitted / sliced? from tensor to matrix or matrix to vector?" if we think it could be beneficial why not? --> but here we should first implement the slicing which should using the Span< T > stuff. 
- ICollection< T > --> ok here we have the problem that a collection can add elements. sounds easy but .... here my question "do we allow heterogeneous tensors? which is actual possible with jagged arrays but never with multidimensional? Something like ok 3 rows but 1st row has 2 columns, 2nd has 3 columns and 3rd das 4?"

Thanks for your though and I again say it "it is not functional important but i just want to start an issue t collect thoughts about this topic". ;)

**Comment by Oceania2018** [comment]
I would say let’s do IList<T>, IList is with more methods which is convinent for user.

**Comment by Nucs** [comment]
`NDArray` currently implements `IEnumerable<T>`.
