### ISSUE TITLE
Implement numpy.exp

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#76]
Calculate the exponential of all elements in the input array.
https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.exp.html

**Comment by Nucs** [comment]
This issue has been implemented in the [new release](https://github.com/SciSharp/NumSharp/pull/336) of NumSharp 0.11.0-alpha2 and available on [nuget](https://www.nuget.org/packages/NumSharp/0.11.0-alpha2).
