### ISSUE TITLE
Implement numpy.concatenate

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#81]
Join a sequence of arrays along an existing axis.
https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.concatenate.html

**Comment by Oceania2018** [comment]
@vunb Could you do this one?

**Comment by vunb** [comment]
Okay. I will do it tomorrow

**Comment by natank1** [comment]
Hi
Indeed there is concatenate but it is unclear the right way to do it ? I have numpy matrix X with the shape 7000x600.

I want to extract  x1= X[: ,np.concatenate((np.arange(30),np.arange(55,79)))] , namely the entire rows only the columns 0 to 30 and the 55 to 79. How do I do it in numsharp

**Comment by Nucs** [comment]
Slicing in NumSharp does not support an `ndarray` inside a slice indexer
I think it is more practical to slice columns 0 to 30, then slice columns 55 to 79 and finally to concatenate them.
```Python
a = X[":, 0:30"]
b = X[":, 55:79"]
ret = np.concatenate(a,b)
```

**Comment by natank1** [comment]
Thanks

Your code does not work . It states in the concatenate that it cannot
convert NDarray to NDarray[] . and it cannot convert in the second argument
NDarray to int. I tried to define both of them as var. but it did not help.
One more thing that I wish to understand: If I dont know the columns in
advance (I calculate them from somwehre) what do I do (I cannot right
string ":,0:30" because I dont know what is the value of 30)

**Comment by henon** [comment]
@natank1 from your reported error message I would say that you should call it like this:

var ret = np.concatenate(new NDArray[]{a,b});

@Nucs 
Here is a good testcase for the concatenate function. Don't want to mess with the code base now, so putting it here.
```C#
        [TestMethod]
        public void concatenateTest()
        {
            var a = np.array(new[,] {{1, 2}, {3, 4}});
            var b = np.array(new[,] {{5, 6}});
            var given = np.concatenate(new[] {a, b}, axis: 0);
            var expected =
                "array([[1, 2],\n" +
                "       [3, 4],\n" +
                "       [5, 6]])";
            Assert.AreEqual(expected, given.repr);
            given = np.concatenate(new[]{a, b.T}, axis: 1);
            expected =
                "array([[1, 2, 5],\n" +
                "       [3, 4, 6]])";
            Assert.AreEqual(expected, given.repr);
            given = np.concatenate(new[]{a, b}, axis: null);
            expected =
                "array([1, 2, 3, 4, 5, 6])";
            Assert.AreEqual(expected, given.repr);
        }
```

**Comment by natank1** [comment]
Thanks both of you
